airflow:
  image:
    repository: ci-dump-dcr.mfb.io/data/airflow
    tag: latest
  executor: Local
  service:
    type: NodePort
  config:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: true
    AIRFLOW__CORE__DAG_RUN_CONF_OVERRIDES_PARAMS: true
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 30
    AIRFLOW__KUBERNETES__NAMESPACE: default
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgresql:5432/airflow
    POSTGRES_HOST: airflow-postgresql
    ENV: unknown

web:
  initialStartupDelay: "10"
  initialDelaySeconds: "10"

postgresql:
  enabled: true
  postgresqlUsername: airflow
  postgresqlDatabase: airflow
  postgresqlPassword: airflow

logsPersistence:
  accessMode: ReadWriteOnce
  size: 1Gi

## Create or use ServiceAccount
serviceAccount:
  create: false
  name: airflow