apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow-helm.fullname" . }}
  labels:
    app: {{ include "airflow-helm.fullname" . }}
    app.kubernetes.io/name: {{ include "airflow-helm.fullname" . }}
    helm.sh/chart: {{ include "airflow-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    expose: http
    access: company
spec:
  type: {{ .Values.airflow.service.type }}
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    app: {{ include "airflow-helm.fullname" . }}
    app.kubernetes.io/name: {{ include "airflow-helm.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
